# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
      demands:
        - agent.name -equals PipelineAgent
    steps:
    - task: PowerShell@2
      displayName: 'Check if Docker is running'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Checking if Docker is running..."
          try {
            docker version | Out-Null
            Write-Host "Docker is running."
          }
          catch {
            Write-Error "Docker is not running. Please start Docker Desktop before running the pipeline."
            exit 1
          }
    - task: Docker@2
      displayName:  'Build server Docker image'
      inputs:
        command: 'build'
        Dockerfile: 'Server/Dockerfile'
        tags: |
          server: local
    - task: Docker@2
      displayName:  'Build Client Docker image'
      inputs:
        command: 'build'
        Dockerfile: 'Client/Dockerfile'
        tags: |
          client: local
